import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { AppWindow, Code2, Download, Gamepad2, Globe2, Play, RefreshCw, Sparkles, Wand2, Zap } from "lucide-react";
import JSZip from "jszip";

export const Route = createFileRoute("/ai-builders")({
  head: () => ({ meta: [{ title: "AI Builders — Website · Game · App" }, { name: "description", content: "Build websites, games and web apps from a prompt with live previews and ZIP export." }] }),
  component: AiBuildersPage,
});

type BuilderKind = "website" | "game" | "app";

type Project = {
  kind: BuilderKind;
  name: string;
  html: string;
  css: string;
  js: string;
  readme: string;
};

const tabs: { id: BuilderKind; label: string; icon: typeof Globe2; description: string }[] = [
  { id: "website", label: "AI Website Builder", icon: Globe2, description: "Site + design + code + aperçu en direct" },
  { id: "game", label: "AI Game Creator", icon: Gamepad2, description: "Petit jeu jouable directement dans la plateforme" },
  { id: "app", label: "AI App Builder", icon: AppWindow, description: "Application web + aperçu + export ZIP" },
];

const escapeHtml = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[char] || char);

function makeWebsite(prompt: string): Project {
  const p = prompt.trim() || "un restaurant marocain moderne";
  const title = p.replace(/^crée-moi\s+(un|une)\s+/i, "").slice(0, 60);
  const html = `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title></head><body><main class="hero"><nav><strong>MAISON</strong><div><a href="#menu">Menu</a><a href="#about">À propos</a><a href="#contact">Contact</a></div></nav><section><span class="eyebrow">AI WEBSITE BUILDER</span><h1>${escapeHtml(title)}</h1><p>Une expérience digitale moderne, élégante et pensée pour convertir les visiteurs.</p><div class="actions"><a class="primary" href="#menu">Découvrir</a><a class="secondary" href="#contact">Réserver</a></div></section></main><section id="menu" class="cards"><article><span>01</span><h2>Signature</h2><p>Une offre mise en avant avec une présentation premium.</p></article><article><span>02</span><h2>Expérience</h2><p>Un parcours clair, rapide et adapté au mobile.</p></article><article><span>03</span><h2>Contact</h2><p>Des appels à l'action visibles et faciles à utiliser.</p></article></section><footer id="contact">Créé avec AI Creative Studio</footer></body></html>`;
  const css = `*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#0b0b0d;color:#fff}.hero{min-height:72vh;padding:28px 7vw;background:radial-gradient(circle at 80% 20%,#6d3df455,transparent 35%),linear-gradient(135deg,#11111a,#09090b)}nav{display:flex;justify-content:space-between;align-items:center}nav div{display:flex;gap:24px}a{color:inherit;text-decoration:none}.hero section{max-width:800px;padding:15vh 0}.eyebrow{font-size:11px;letter-spacing:.25em;color:#b9a8ff}.hero h1{font-size:clamp(44px,8vw,92px);line-height:.95;margin:18px 0}.hero p{font-size:18px;color:#aaa;max-width:620px}.actions{display:flex;gap:12px;margin-top:30px}.primary,.secondary{padding:14px 20px;border-radius:14px}.primary{background:#fff;color:#09090b}.secondary{border:1px solid #ffffff25}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:70px 7vw;background:#101014}.cards article{padding:28px;border:1px solid #ffffff12;border-radius:24px;background:#ffffff06}.cards span{color:#9f87ff;font-size:12px}.cards h2{font-size:28px}.cards p{color:#999;line-height:1.6}footer{padding:40px 7vw;color:#777}@media(max-width:800px){.cards{grid-template-columns:1fr}nav div{display:none}}`;
  return { kind: "website", name: title || "AI Website", html, css, js: "document.querySelectorAll('a[href^=\"#\"]').forEach(a=>a.addEventListener('click',e=>{const target=document.querySelector(a.getAttribute('href'));if(target){e.preventDefault();target.scrollIntoView({behavior:'smooth'});}}));", readme: `# ${title}\n\nGenerated by AI Website Builder.\nPrompt: ${p}\n` };
}

function makeGame(prompt: string): Project {
  const p = prompt.trim() || "un petit jeu de collecte de pièces";
  const html = `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI Game</title></head><body><div class="hud"><strong>AI GAME</strong><span>Score: <b id="score">0</b></span><button id="restart">Rejouer</button></div><canvas id="game" width="900" height="520"></canvas><p class="hint">Utilise ← → ou A/D pour déplacer le joueur. Collecte les étoiles. ${escapeHtml(p)}</p></body></html>`;
  const css = `body{margin:0;min-height:100vh;background:#08080b;color:#fff;font-family:system-ui;display:grid;place-items:center;padding:20px}.hud{width:min(900px,100%);display:flex;gap:18px;align-items:center;margin-bottom:12px}.hud strong{margin-right:auto}.hud button{border:1px solid #ffffff20;background:#ffffff08;color:#fff;border-radius:10px;padding:9px 13px}canvas{width:100%;max-width:900px;border-radius:24px;border:1px solid #ffffff15;background:radial-gradient(circle at 50% 30%,#3a2566,#0c0c12)}.hint{color:#888;text-align:center}`;
  const js = `const c=document.getElementById('game'),x=c.getContext('2d'),scoreEl=document.getElementById('score');let score=0,player={x:450,y:440,w:46,h:20,s:7},keys={};let stars=[];function spawn(){stars=[...Array(8)].map(()=>({x:30+Math.random()*840,y:50+Math.random()*340,r:9}))}function reset(){score=0;player.x=450;spawn();scoreEl.textContent=score}addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);document.getElementById('restart').onclick=reset;function loop(){if(keys['arrowleft']||keys.a)player.x-=player.s;if(keys['arrowright']||keys.d)player.x+=player.s;player.x=Math.max(0,Math.min(900-player.w,player.x));x.clearRect(0,0,900,520);stars.forEach((s,i)=>{x.fillStyle='#f6d365';x.beginPath();x.arc(s.x,s.y,s.r,0,Math.PI*2);x.fill();if(s.x>player.x&&s.x<player.x+player.w&&Math.abs(s.y-player.y)<20){stars.splice(i,1);score++;scoreEl.textContent=score}});x.fillStyle='#fff';x.fillRect(player.x,player.y,player.w,player.h);requestAnimationFrame(loop)}reset();loop();`;
  return { kind: "game", name: "AI Game", html, css, js, readme: `# AI Game Creator\n\nPrompt: ${p}\n\nOpen index.html in a browser to play.\n` };
}

function makeApp(prompt: string): Project {
  const p = prompt.trim() || "une application de gestion de tâches moderne";
  const html = `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI App</title></head><body><div id="app"></div></body></html>`;
  const css = `body{margin:0;background:#f6f6f8;color:#17171b;font-family:Inter,system-ui,sans-serif}.shell{max-width:900px;margin:0 auto;padding:50px 20px}.top{display:flex;justify-content:space-between;align-items:center}.badge{font-size:11px;background:#111;color:#fff;padding:8px 12px;border-radius:999px}.card{margin-top:28px;background:#fff;border:1px solid #e7e7eb;border-radius:24px;padding:22px;box-shadow:0 18px 50px #00000008}.row{display:flex;gap:10px}.row input{flex:1;padding:13px;border:1px solid #ddd;border-radius:12px}.row button{border:0;background:#5b3df5;color:#fff;border-radius:12px;padding:0 18px}.item{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid #eee}.muted{color:#777}`;
  const js = `const root=document.getElementById('app');root.innerHTML='<div class="shell"><div class="top"><div><strong>AI APP BUILDER</strong><h1>${escapeHtml(p)}</h1></div><span class="badge">LIVE</span></div><div class="card"><div class="row"><input id="task" placeholder="Ajouter un élément…"><button id="add">Ajouter</button></div><div id="list"></div></div></div>';const list=document.getElementById('list');document.getElementById('add').onclick=()=>{const input=document.getElementById('task');if(!input.value.trim())return;const row=document.createElement('div');row.className='item';row.innerHTML='<span>'+input.value.replace(/[&<>]/g,'')+'</span><button>✓</button>';row.querySelector('button').onclick=()=>row.remove();list.appendChild(row);input.value='';};`;
  return { kind: "app", name: "AI App", html, css, js, readme: `# AI App Builder\n\nPrompt: ${p}\n\nThis is a standalone web app scaffold generated by AI Creative Studio.\n` };
}

function buildProject(kind: BuilderKind, prompt: string) { return kind === "website" ? makeWebsite(prompt) : kind === "game" ? makeGame(prompt) : makeApp(prompt); }

function Preview({ project }: { project: Project | null }) {
  const srcDoc = useMemo(() => project ? `${project.html.replace('</head>', `<style>${project.css}</style></head>`).replace('</body>', `<script>${project.js.replace(/<\/script/gi, '<\\/script>')}</script></body>`)}` : "", [project]);
  if (!project) return <div className="grid min-h-[500px] place-items-center rounded-3xl border border-white/10 bg-black/30 text-sm text-white/30">L'aperçu apparaîtra ici.</div>;
  return <iframe title="AI Builder live preview" srcDoc={srcDoc} className="min-h-[560px] w-full rounded-3xl border border-white/10 bg-white" sandbox="allow-scripts" />;
}

function AiBuildersPage() {
  const [kind, setKind] = useState<BuilderKind>("website");
  const [prompt, setPrompt] = useState("Crée-moi un site pour un restaurant marocain moderne");
  const [project, setProject] = useState<Project | null>(() => makeWebsite("Crée-moi un site pour un restaurant marocain moderne"));
  const [busy, setBusy] = useState(false);
  const active = tabs.find(t => t.id === kind)!;

  const generate = () => { setBusy(true); window.setTimeout(() => { setProject(buildProject(kind, prompt)); setBusy(false); }, 350); };
  const switchKind = (next: BuilderKind) => { setKind(next); setProject(null); setPrompt(next === "website" ? "Crée-moi un site pour un restaurant marocain moderne" : next === "game" ? "Crée un jeu de collecte de pièces dans un monde futuriste" : "Crée une application web moderne de gestion de tâches"); };
  const exportZip = async () => {
    if (!project) return;
    const zip = new JSZip();
    zip.file("index.html", project.html.replace('</head>', `<link rel="stylesheet" href="style.css"></head>`).replace('</body>', `<script src="script.js"></script></body>`));
    zip.file("style.css", project.css);
    zip.file("script.js", project.js);
    zip.file("README.md", project.readme);
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `${project.name.toLowerCase().replace(/[^a-z0-9]+/g, "-") || "ai-project"}.zip`; a.click(); URL.revokeObjectURL(url);
  };
  return <main className="min-h-screen bg-[#07070a] text-white"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><a href="/ai-hub" className="grid size-10 place-items-center rounded-xl border border-white/10 bg-white/[.04]">←</a><div className="grid size-10 place-items-center rounded-xl bg-white text-black"><Sparkles className="size-5" /></div><div><h1 className="text-xl font-semibold">AI Builder Studio</h1><p className="text-xs text-white/40">Website · Game · App · Live Preview · ZIP</p></div></div><a href="/ai-workspace" className="rounded-xl bg-white px-4 py-2 text-xs font-semibold text-black">AI Workspace</a></header>
    <div className="mt-6 grid gap-4 lg:grid-cols-[290px_1fr]">
      <aside className="rounded-3xl border border-white/10 bg-white/[.03] p-3"><p className="px-3 pb-2 text-[10px] uppercase tracking-[.2em] text-white/30">Create</p>{tabs.map(t=>{const I=t.icon;return <button key={t.id} onClick={()=>switchKind(t.id)} className={`mb-2 w-full rounded-2xl p-4 text-left ${kind===t.id?"bg-white text-black":"hover:bg-white/[.05]"}`}><div className="flex items-center gap-3"><I className="size-5"/><div><div className="text-xs font-semibold">{t.label}</div><div className={`mt-1 text-[10px] ${kind===t.id?"text-black/50":"text-white/35"}`}>{t.description}</div></div></div></button>})}</aside>
      <section className="min-w-0"><div className="rounded-3xl border border-white/10 bg-white/[.03] p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-violet-200"><Wand2 className="size-4"/><span className="text-[10px] uppercase tracking-[.2em]">{active.label}</span></div><h2 className="mt-2 text-2xl font-semibold">Décris ce que tu veux construire</h2><p className="mt-1 text-xs text-white/40">L'éditeur prépare une interface, le code et un aperçu interactif.</p></div><div className="flex gap-2"><button onClick={generate} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-blue-500 px-5 py-3 text-xs font-bold">{busy?<RefreshCw className="size-4 animate-spin"/>:<Zap className="size-4"/>}{busy?"Génération…":"Générer"}</button><button onClick={exportZip} disabled={!project} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-xs font-semibold disabled:opacity-30"><Download className="size-4"/>Export ZIP</button></div></div>
      <textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={5} className="mt-5 w-full rounded-2xl border border-white/10 bg-black/30 p-4 text-sm outline-none" placeholder={kind==="website"?"Ex. Crée-moi un site pour un restaurant marocain moderne":kind==="game"?"Ex. Crée un jeu de course futuriste…":"Ex. Crée une application de gestion de tâches…"}/>
      <div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-white/40">Code généré</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-white/40">Live Preview</span><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-white/40">Mobile responsive</span>{kind!=="website"&&<span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-white/40">Playable / interactive</span>}</div>
      </div>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Play className="size-4"/>Aperçu en direct</div><Preview project={project}/></div><div className="rounded-3xl border border-white/10 bg-[#0b0b0f] p-4"><div className="mb-3 flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-semibold"><Code2 className="size-4"/>Code généré</div><span className="text-[10px] text-white/25">HTML · CSS · JS</span></div><pre className="max-h-[560px] overflow-auto whitespace-pre-wrap rounded-2xl bg-black/30 p-4 text-[10px] leading-5 text-white/55">{project ? `// index.html\n${project.html}\n\n/* style.css */\n${project.css}\n\n// script.js\n${project.js}` : "Génère un projet pour afficher le code."}</pre></div></div>
    </section></div></div></main>;
}
