import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Bot, Boxes, ChevronRight, Clock3, Code2, FileText, GitBranch, Globe2, Layers3, Music2, Play, Plus, Share2, Sparkles, Store, Wand2, Workflow, Zap } from "lucide-react";
import { FAL_TOOLS } from "@/lib/fal.functions";

export const Route = createFileRoute("/ai-hub")({
  head: () => ({ meta: [{ title: "AI Hub — Creative Suite" }, { name: "description", content: "AI agents, workflows, social studio, models and creative tools." }] }),
  component: AiHubPage,
});

type Feature = { id: string; label: string; icon: any; description: string };
const features: Feature[] = [
  { id: "agent", label: "AI Agent", icon: Bot, description: "Construis une tâche complète et lance plusieurs outils IA." },
  { id: "editor", label: "AI Video Editor", icon: Play, description: "Crée automatiquement un plan de montage à partir d'une vidéo." },
  { id: "dubbing", label: "AI Dubbing", icon: Globe2, description: "Prépare traduction, voix et lip-sync pour une vidéo." },
  { id: "avatar", label: "AI Avatar Studio", icon: Bot, description: "Script, voix, avatar et synchronisation dans un seul espace." },
  { id: "music", label: "AI Music Studio", icon: Music2, description: "Génère des briefs musicaux et effets sonores." },
  { id: "social", label: "Social Media Studio", icon: Share2, description: "Transforme une idée en pack TikTok, Reels et Shorts." },
  { id: "prompts", label: "Prompt Library", icon: Wand2, description: "Prompts variables, favoris, templates et recherche." },
  { id: "workflow", label: "Workflow Builder", icon: Workflow, description: "Assemble des blocs Image → Video → Voice → Music." },
  { id: "usage", label: "Usage Dashboard", icon: Clock3, description: "Visualise l'activité locale de ton Workspace." },
  { id: "models", label: "Models Marketplace", icon: Store, description: "Explore tous les modèles FAL déjà configurés." },
];

const read = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) || "null") ?? fallback; } catch { return fallback; } };
const write = (key: string, value: unknown) => localStorage.setItem(key, JSON.stringify(value));

function AiHubPage() {
  const [active, setActive] = useState("agent");
  return <main className="min-h-screen bg-[#08080a] text-white">
    <div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-8">
      <header className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3"><a href="/ai-workspace" className="grid size-10 place-items-center rounded-xl border border-white/10 bg-white/[.04]">←</a><div className="grid size-10 place-items-center rounded-xl bg-white text-black"><Sparkles className="size-5" /></div><div><h1 className="text-xl font-semibold">AI Creative Hub</h1><p className="text-xs text-white/40">Agents · workflows · social · models · production</p></div></div>
        <div className="flex gap-2"><a href="/chatgpt-plugin" className="rounded-xl border border-violet-400/20 bg-violet-400/10 px-4 py-2 text-xs font-semibold text-violet-100">ChatGPT App</a><a href="/ai-builders" className="rounded-xl border border-white/10 px-4 py-2 text-xs font-semibold">AI Builders</a><a href="/ai-workspace" className="rounded-xl bg-white px-4 py-2 text-xs font-semibold text-black">Open AI Workspace</a></div>
      </header>

      <div className="mt-6 grid gap-4 lg:grid-cols-[250px_1fr]">
        <aside className="rounded-3xl border border-white/10 bg-white/[.03] p-3">
          <p className="px-3 pb-2 text-[10px] uppercase tracking-[.2em] text-white/30">Creative tools</p>
          {features.map(f => { const I = f.icon; return <button key={f.id} onClick={() => setActive(f.id)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl p-3 text-left ${active === f.id ? "bg-white text-black" : "hover:bg-white/[.05]"}`}><I className="size-4" /><span className="min-w-0"><span className="block text-xs font-semibold">{f.label}</span><span className={`block text-[10px] ${active === f.id ? "text-black/45" : "text-white/30"}`}>{f.description}</span></span></button>; })}
        </aside>
        <section>{active === "agent" ? <Agent /> : active === "editor" ? <VideoEditor /> : active === "dubbing" ? <Dubbing /> : active === "avatar" ? <Avatar /> : active === "music" ? <Music /> : active === "social" ? <Social /> : active === "prompts" ? <PromptLibrary /> : active === "workflow" ? <WorkflowBuilder /> : active === "usage" ? <Usage /> : <Models />}</section>
      </div>
    </div>
  </main>;
}

function Panel({ title, icon: Icon, children }: any) { return <div className="rounded-3xl border border-white/10 bg-white/[.03] p-5 sm:p-7"><div className="mb-5 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-violet-400/10 text-violet-200"><Icon className="size-5" /></span><div><h2 className="text-lg font-semibold">{title}</h2></div></div>{children}</div>; }
function Agent() { const [goal,setGoal]=useState(""); const [plan,setPlan]=useState<string[]>([]); const make=()=>setPlan(["Analyze the request","Generate visual concept with Image AI","Animate the best result with Video AI","Generate voice with ElevenLabs","Generate music / sound effects","Assemble final creative output"]); return <Panel title="AI Agent" icon={Bot}><textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={5} placeholder="Ex. Crée une publicité de 15 secondes pour une voiture futuriste…" className="w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-sm outline-none"/><button onClick={make} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black"><Zap className="size-4"/>Build agent plan</button>{plan.length>0&&<div className="mt-5 space-y-2">{plan.map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-3 text-xs"><span className="grid size-6 place-items-center rounded-full bg-violet-400/10 text-violet-200">{i+1}</span>{x}</div>)}</div>}</Panel> }
function VideoEditor(){ const [text,setText]=useState(""); const [plan,setPlan]=useState<string[]>([]); return <Panel title="AI Video Editor" icon={Play}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Décris le style du montage…" className="w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none"/><button onClick={()=>setPlan(["Detect scenes", "Remove silence", "Create captions", "Choose highlights", "Add transitions", "Export vertical + horizontal"])} className="mt-3 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Create edit plan</button>{plan.length>0&&<div className="mt-4 grid gap-2 sm:grid-cols-2">{plan.map(x=><div className="rounded-xl border border-white/10 p-3 text-xs" key={x}>✓ {x}</div>)}</div>}</Panel> }
function Dubbing(){ const [lang,setLang]=useState("English"); return <Panel title="AI Dubbing" icon={Globe2}><div className="grid gap-3 sm:grid-cols-2"><input placeholder="Video URL / upload" className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/><select value={lang} onChange={e=>setLang(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs"><option>English</option><option>French</option><option>Spanish</option><option>Arabic</option><option>German</option></select></div><div className="mt-4 rounded-2xl border border-white/10 p-4 text-xs text-white/50">Pipeline: transcription → translation → voice generation → lip-sync → export.</div><button className="mt-3 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Prepare dubbing in {lang}</button></Panel> }
function Avatar(){ return <Panel title="AI Avatar Studio" icon={Bot}><div className="grid gap-3 sm:grid-cols-3"><input placeholder="Avatar image" className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/><input placeholder="Script" className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs sm:col-span-2"/><select className="rounded-xl border border-white/10 bg-black/20 p-3 text-xs"><option>ElevenLabs voice</option><option>Custom voice</option></select></div><button className="mt-4 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Build avatar workflow</button></Panel> }
function Music(){ const [prompt,setPrompt]=useState(""); return <Panel title="AI Music Studio" icon={Music2}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={5} placeholder="Cinematic trap, dark futuristic, 15 seconds…" className="w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-sm outline-none"/><div className="mt-3 flex flex-wrap gap-2">{["Cinematic","Hip-Hop","Trap","EDM","Lo-fi","Ambient"].map(x=><button onClick={()=>setPrompt(x+" — ")} key={x} className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] text-white/55">{x}</button>)}</div><button className="mt-4 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Generate music brief</button></Panel> }
function Social(){ const [topic,setTopic]=useState(""); const [pack,setPack]=useState<any>(null); return <Panel title="Social Media Studio" icon={Share2}><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Produit ou sujet" className="w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none"/><button onClick={()=>setPack({script:`Hook → problem → solution → CTA pour ${topic || "ton produit"}`,title:`Découvre ${topic || "ce produit"}`,hashtags:`#ai #creative #${(topic||"product").replace(/\s+/g,"").toLowerCase()}`})} className="mt-3 rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black">Generate social pack</button>{pack&&<div className="mt-5 grid gap-3 sm:grid-cols-3">{Object.entries(pack).map(([k,v])=><div className="rounded-2xl border border-white/10 p-4" key={k}><p className="text-[10px] uppercase text-white/30">{k}</p><p className="mt-2 text-xs text-white/70">{String(v)}</p></div>)}</div>}</Panel> }
function PromptLibrary(){ const [items,setItems]=useState(()=>read<any[]>("ai-prompts",[])); const [text,setText]=useState(""); const save=()=>{if(!text.trim())return; const next=[{id:crypto.randomUUID(),text,createdAt:Date.now()},...items];setItems(next);write("ai-prompts",next);setText("")}; return <Panel title="Prompt Library" icon={Wand2}><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Nouveau prompt…" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black/20 p-3 text-sm outline-none"/><button onClick={save} className="grid size-11 place-items-center rounded-xl bg-white text-black"><Plus className="size-4"/></button></div><div className="mt-4 space-y-2">{items.map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3 text-xs text-white/60">{x.text}</div>)}</div></Panel> }
function WorkflowBuilder(){ const [nodes,setNodes]=useState(["Prompt"]); const add=(x:string)=>setNodes(n=>[...n,x]); return <Panel title="AI Workflow Builder" icon={Workflow}><div className="flex flex-wrap gap-2">{["Image","Video","Voice","Music","3D","Upscale","Publish"].map(x=><button key={x} onClick={()=>add(x)} className="rounded-xl border border-white/10 px-3 py-2 text-xs hover:bg-white/[.06]">+ {x}</button>)}</div><div className="mt-6 flex flex-wrap items-center gap-2">{nodes.map((n,i)=><div key={i} className="flex items-center gap-2"><div className="rounded-2xl border border-violet-400/20 bg-violet-400/10 px-4 py-3 text-xs">{n}</div>{i<nodes.length-1&&<ChevronRight className="size-4 text-white/25"/>}</div>)}</div><button onClick={()=>setNodes(["Prompt"])} className="mt-5 rounded-xl border border-white/10 px-4 py-2 text-xs">Reset workflow</button></Panel> }
function Usage(){ const history=read<any[]>("ai-history",[]); const by=history.reduce((a,x)=>(a[x.category]=(a[x.category]||0)+1,a),{} as Record<string,number>); return <Panel title="Usage Dashboard" icon={Clock3}><div className="grid gap-3 sm:grid-cols-4">{[["Generations",history.length],["Image",by.Image||0],["Video",by.Video||0],["Audio",by.Audio||0]].map(([k,v])=><div className="rounded-2xl border border-white/10 p-4" key={String(k)}><p className="text-[10px] text-white/30">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div><p className="mt-4 text-[11px] text-white/30">Les métriques se basent sur l'historique du navigateur. Connecte-les à Supabase pour un dashboard multi-utilisateur.</p></Panel> }
function Models(){ const groups=useMemo(()=>Object.entries(FAL_TOOLS.reduce((a,x)=>(a[x.category]??=[],a[x.category].push(x),a),{} as Record<string,typeof FAL_TOOLS>)),[]); return <Panel title="Models Marketplace" icon={Store}><div className="space-y-6">{groups.map(([cat,tools])=><div key={cat}><h3 className="mb-2 text-xs font-semibold uppercase tracking-widest text-white/35">{cat}</h3><div className="grid gap-2 sm:grid-cols-2">{tools.map(t=><div key={t.id} className="rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between"><span className="text-xs font-semibold">{t.label}</span><span className="rounded-full bg-white/[.05] px-2 py-1 text-[9px] text-white/35">FAL</span></div><p className="mt-1 text-[10px] text-white/35">{t.model}</p><p className="mt-2 text-[10px] text-white/50">{t.description}</p></div>)}</div></div>)}</div></Panel> }
